Repository VM-Chinese-translate-group/MCE2, pull requests merged in 2025-07, with the labels that each got.

#21 狂怒模组汉化
  CNPack/kubejs/assets/rage/lang/en_us.json
  CNPack/kubejs/assets/rage/lang/zh_cn.json
Labels: approve, resource

#29 【维护】整合包1.1.0.2更新同步
  .gitignore
  .vscode/extensions.json
  CNPack/config/configurableextramobdrops/mobdropconfig.txt
  CNPack/config/ftbquests/quests/chapters/3the_great_below.snbt
  CNPack/config/ftbquests/quests/chapters/6ars_nouveau.snbt
  CNPack/config/ftbquests/quests/chapters/6modular_tools.snbt
  CNPack/config/ftbquests/quests/chapters/6storage_solutions.snbt
  CNPack/config/ftbquests/quests/chapters/6transport__quick_travel.snbt
  CNPack/config/ftbquests/quests/chapters/advanced_mekanism.snbt
  CNPack/config/ftbquests/quests/chapters/animal_compendium.snbt
  CNPack/config/ftbquests/quests/chapters/bosses.snbt
  CNPack/config/ftbquests/quests/chapters/botania.snbt
  CNPack/config/ftbquests/quests/chapters/challenges.snbt
  CNPack/config/ftbquests/quests/chapters/clthe_nether.snbt
  CNPack/config/ftbquests/quests/chapters/complicated_bees.snbt
  CNPack/config/ftbquests/quests/chapters/create.snbt
  CNPack/config/ftbquests/quests/chapters/eapplied_energistics_2.snbt
  CNPack/config/ftbquests/quests/chapters/ethe_bumblezone.snbt
  CNPack/config/ftbquests/quests/chapters/introduction.snbt
  CNPack/config/ftbquests/quests/chapters/little_logistics.snbt
  CNPack/config/ftbquests/quests/chapters/mayor_position_available.snbt
  CNPack/config/ftbquests/quests/chapters/mekanism.snbt
  CNPack/config/ftbquests/quests/chapters/rats.snbt
  CNPack/config/ftbquests/quests/chapters/space_exploration.snbt
  CNPack/config/ftbquests/quests/chapters/thermal.snbt
  CNPack/kubejs/assets/kubejs/lang/en_us.json
  CNPack/kubejs/assets/tinkertantrum/lang/en_us.json
  CNPack/kubejs/assets/tips/tips/greatbelow.json
  CNPack/kubejs/assets/tips/tips/mp1.json
  CNPack/kubejs/assets/xaerominimap/lang/en_us.json
  CNPack/kubejs/assets/xaeroworldmap/lang/en_us.json
  CNPack/kubejs/client_scripts/tooltips.js
  CNPack/kubejs/data/titles/titles/bee.json
  CNPack/kubejs/data/titles/titles/conductor.json
  CNPack/kubejs/data/titles/titles/die.json
  CNPack/kubejs/data/titles/titles/gene.json
  CNPack/kubejs/data/titles/titles/gobby.json
  CNPack/kubejs/data/titles/titles/lil.json
  CNPack/kubejs/data/titles/titles/mage.json
  CNPack/kubejs/data/titles/titles/mayor.json
  CNPack/kubejs/data/titles/titles/monarch.json
  CNPack/kubejs/data/titles/titles/pilot.json
  CNPack/kubejs/data/titles/titles/proud.json
  CNPack/kubejs/data/titles/titles/sticky.json
  CNPack/kubejs/server_scripts/palantir_behavior.js
  CNPack/kubejs/startup_scripts/custom_item_registry.js
  CNPack/modpackinfo.json
  README.md
Labels: ftbquest, Need Review, kubejs

#34 piglinproliferation模组修正
  CNPack/kubejs/assets/piglinproliferation/lang/zh_cn.json
Labels: approve

#32 教程对话翻译
  CNPack/kubejs/assets/dialog/lang/en_us.json
Labels: approve

#41 stardew_fishing汉化
  CNPack/kubejs/assets/stardew_fishing/lang/en_us.json
Labels: approve

#42 feat(translate): Add Xaero's maps mod translation
  CNPack/kubejs/assets/biofactory/lang/zh_cn.json
  CNPack/kubejs/assets/bosses_of_mass_destruction/lang/zh_cn.json
  CNPack/kubejs/assets/cataclysm/lang/zh_cn.json
  CNPack/kubejs/assets/cgs/lang/en_us.json
  CNPack/kubejs/assets/dialog/lang/zh_cn.json
  CNPack/kubejs/assets/milkablecreepers/lang/zh_cn.json
  CNPack/kubejs/assets/netherportalconfigurator/lang/zh_cn.json
  CNPack/kubejs/assets/stardew_fishing/lang/zh_cn.json
  CNPack/kubejs/assets/xaerominimap/lang/en_us.json
  CNPack/kubejs/assets/xaerominimap/lang/zh_cn.json
  CNPack/kubejs/assets/xaeroworldmap/lang/en_us.json
  CNPack/kubejs/assets/xaeroworldmap/lang/zh_cn.json
Labels: Need Review

#38 data-mce奖励箱翻译
  CNPack/kubejs/data/mce/loot_modifiers/inject_quest_crates.json
Labels: Need Review, kubejs

#31 佳发工坊模组汉化
  CNPack/kubejs/assets/jaffactory/lang/en_us.json
Labels: approve

#20 每日奖励模组汉化
  CNPack/kubejs/assets/daily_rewards/lang/en_us.json
  CNPack/kubejs/assets/daily_rewards/lang/zh_cnjson
Labels: Need Review

#33 闪烁标语汉化
  CNPack/config/fancymenu/assets/splash.txt
Labels: Need Review, resource

#46 【维护】更新1.1.1.0 任务
  CNPack/config/ftbquests/quests/chapters/3the_great_below.snbt
  CNPack/config/ftbquests/quests/chapters/6ars_nouveau.snbt
  CNPack/config/ftbquests/quests/chapters/6modular_tools.snbt
  CNPack/config/ftbquests/quests/chapters/6nvampirism__vampire.snbt
  CNPack/config/ftbquests/quests/chapters/6storage_solutions.snbt
  CNPack/config/ftbquests/quests/chapters/advanced_mekanism.snbt
  CNPack/config/ftbquests/quests/chapters/animal_compendium.snbt
  CNPack/config/ftbquests/quests/chapters/bosses.snbt
  CNPack/config/ftbquests/quests/chapters/botania.snbt
  CNPack/config/ftbquests/quests/chapters/challenges.snbt
  CNPack/config/ftbquests/quests/chapters/cldifficulty_modes.snbt
  CNPack/config/ftbquests/quests/chapters/clthe_nether.snbt
  CNPack/config/ftbquests/quests/chapters/dev.snbt
  CNPack/config/ftbquests/quests/chapters/eapplied_energistics_2.snbt
  CNPack/config/ftbquests/quests/chapters/ethe_bumblezone.snbt
  CNPack/config/ftbquests/quests/chapters/introduction.snbt
  CNPack/config/ftbquests/quests/chapters/llegendary_artifacts.snbt
  CNPack/config/ftbquests/quests/chapters/mailbox.snbt
  CNPack/config/ftbquests/quests/chapters/mayor_position_available.snbt
  CNPack/config/ftbquests/quests/chapters/mekanism.snbt
  CNPack/config/ftbquests/quests/chapters/mining.snbt
  CNPack/config/ftbquests/quests/chapters/ratlantis.snbt
  CNPack/config/ftbquests/quests/chapters/rats.snbt
  CNPack/config/ftbquests/quests/chapters/space_exploration.snbt
  CNPack/config/ftbquests/quests/chapters/thermal.snbt
  CNPack/config/ftbquests/quests/chapters/vampires_cookbook.snbt
  tools/backfill.py
  tools/fill_quest_texts.py
Labels: approve, ftbquest
